# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instagram_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14instagram_user.proto\"#\n\x12InstagramUserQuery\x12\r\n\x05query\x18\x01 \x01(\t\"\xfc\x02\n\x15InstagramUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tfollowers\x18\x02 \x01(\x05\x12\x11\n\tfollowing\x18\x03 \x01(\x05\x12\x0b\n\x03\x62io\x18\x04 \x01(\t\x12\x19\n\x11\x62usiness_category\x18\x05 \x01(\t\x12\x13\n\x0bis_verified\x18\x06 \x01(\x08\x12\x13\n\x0bvideo_count\x18\x07 \x01(\x05\x12\x1f\n\x17most_recent_video_views\x18\x08 \x01(\x05\x12\x1f\n\x17most_recent_video_likes\x18\t \x01(\x05\x12\x1a\n\x12transparency_label\x18\n \x01(\t\x12\x1d\n\x15\x62usiness_contact_info\x18\x0b \x01(\t\x12\x31\n\x0crecent_posts\x18\x0c \x03(\x0b\x32\x1b.InstagramUserResponse.Post\x1a)\n\x04Post\x12\x10\n\x08post_url\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t2Q\n\rInstagramUser\x12@\n\x11InstagramUserData\x12\x13.InstagramUserQuery\x1a\x16.InstagramUserResponseb\x06proto3')



_INSTAGRAMUSERQUERY = DESCRIPTOR.message_types_by_name['InstagramUserQuery']
_INSTAGRAMUSERRESPONSE = DESCRIPTOR.message_types_by_name['InstagramUserResponse']
_INSTAGRAMUSERRESPONSE_POST = _INSTAGRAMUSERRESPONSE.nested_types_by_name['Post']
InstagramUserQuery = _reflection.GeneratedProtocolMessageType('InstagramUserQuery', (_message.Message,), {
  'DESCRIPTOR' : _INSTAGRAMUSERQUERY,
  '__module__' : 'instagram_user_pb2'
  # @@protoc_insertion_point(class_scope:InstagramUserQuery)
  })
_sym_db.RegisterMessage(InstagramUserQuery)

InstagramUserResponse = _reflection.GeneratedProtocolMessageType('InstagramUserResponse', (_message.Message,), {

  'Post' : _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
    'DESCRIPTOR' : _INSTAGRAMUSERRESPONSE_POST,
    '__module__' : 'instagram_user_pb2'
    # @@protoc_insertion_point(class_scope:InstagramUserResponse.Post)
    })
  ,
  'DESCRIPTOR' : _INSTAGRAMUSERRESPONSE,
  '__module__' : 'instagram_user_pb2'
  # @@protoc_insertion_point(class_scope:InstagramUserResponse)
  })
_sym_db.RegisterMessage(InstagramUserResponse)
_sym_db.RegisterMessage(InstagramUserResponse.Post)

_INSTAGRAMUSER = DESCRIPTOR.services_by_name['InstagramUser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTAGRAMUSERQUERY._serialized_start=24
  _INSTAGRAMUSERQUERY._serialized_end=59
  _INSTAGRAMUSERRESPONSE._serialized_start=62
  _INSTAGRAMUSERRESPONSE._serialized_end=442
  _INSTAGRAMUSERRESPONSE_POST._serialized_start=401
  _INSTAGRAMUSERRESPONSE_POST._serialized_end=442
  _INSTAGRAMUSER._serialized_start=444
  _INSTAGRAMUSER._serialized_end=525
# @@protoc_insertion_point(module_scope)
