# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import instagram_user_pb2 as instagram__user__pb2


class InstagramUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InstagramUserData = channel.unary_unary(
                '/InstagramUser/InstagramUserData',
                request_serializer=instagram__user__pb2.InstagramUserQuery.SerializeToString,
                response_deserializer=instagram__user__pb2.InstagramUserResponse.FromString,
                )


class InstagramUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InstagramUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstagramUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InstagramUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.InstagramUserData,
                    request_deserializer=instagram__user__pb2.InstagramUserQuery.FromString,
                    response_serializer=instagram__user__pb2.InstagramUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InstagramUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InstagramUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InstagramUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InstagramUser/InstagramUserData',
            instagram__user__pb2.InstagramUserQuery.SerializeToString,
            instagram__user__pb2.InstagramUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
